#development:
#  adapter: sqlite3
#  database: db/stringer.sqlite

development:
  template: template0
  adapter: postgresql
  encoding: utf8
  database: stringer_development
  pool: 5
  timeout: 5000
